package KieRule;
import com.example.RuleEngine.order.Order;

rule "HDFC"

when
order : Order(cardType=="HDFC" && price>10000);
then
order.setDiscount(10);
end;


rule "ICICI"

when
order : Order(cardType=="ICICI" && price>10000);
then
order.setDiscount(10);
end;


rule "DBS"

when
order : Order(cardType=="DBS" && price>15000);
then
order.setDiscount(13);
end;

rule "Checking if it's an object"

when
obj : Object(obj!=null)
then
System.out.println("I am an object");
end;

rule "Does an object appear as an order?"

when
Order()
then System.out.println("I identify as an order");
end;